### ISSUE TITLE
KINgaroo issues

### ISSUE THREAD

**Issue by williammarsh94** [DivyaratanPopli/Kinship_Inference#9]
Hi,

I've successfully installed both KIN and KINgaroo, but unfortunately am having issues.

When running kingaroo, I have the required input files, in as far as I can tell the correct format, but am receiving the following error:

![Screenshot 2023-05-03 at 14 55 01](https://user-images.githubusercontent.com/132468603/235937036-a6cbcbc1-f6e2-4bce-b8ae-c136a444a987.png)

I have investigated the output folders, and all are empty. Any suggested trouble shooting?

Best,

William

**Comment by williammarsh94** [comment]
Hi, 

Any thoughts on this?

Best,

William

**Comment by DivyaratanPopli** [comment]
Hi, it's probably because your input files are not in the expected format. Can you compare your files to the examples files and make sure they follow the guidelines in README? Also, it seems like you're using an old version. You can download and install from github as shown in README just to be sure.
